services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  
  streamlit:
    build: ./streamlit
    container_name: streamlit
    init: true
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - ./streamlit/embedding_generator.py:/app/embedding_generator.py